# Generated by Django 4.0.1 on 2024-02-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='OpTeam',
        ),
        migrations.RemoveField(
            model_name='order',
            name='WareTeams',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='season',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sortno',
            new_name='productno',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Drop',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
