# Generated by Django 4.0.1 on 2024-03-01 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_remove_order_opteam_remove_order_wareteams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_warteam', models.BooleanField(default=False)),
                ('is_opsteam', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('assigned_to', models.ManyToManyField(related_name='notifications_assigned', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
