# Generated by Django 4.0.1 on 2024-03-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='notification',
            name='assigned_to',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
