# Generated by Django 4.0.1 on 2024-03-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_notification_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='assigned_to',
        ),
    ]
