# Generated by Django 4.0.1 on 2024-03-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_manager_id_wareteams_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='opteam',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.manager'),
        ),
    ]
