# Generated by Django 4.0.1 on 2024-03-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_vendorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='image',
            field=models.ImageField(blank=True, upload_to='vendorrequest'),
        ),
    ]
