# Generated by Django 4.0.1 on 2024-03-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRequestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_request_images')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.vendorrequest')),
            ],
        ),
    ]
