# Generated by Django 4.0.1 on 2024-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_vendorrequestimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='product',
            field=models.CharField(max_length=256),
        ),
    ]
