# Generated by Django 4.0.1 on 2024-03-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_productdeleted_productlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlogs',
            name='action',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
