# Generated by Django 4.0.1 on 2024-03-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_productlogs_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, upload_to='qr')),
            ],
        ),
    ]
