# Generated by Django 4.0.1 on 2024-03-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_notification_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opteam',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.manager'),
        ),
        migrations.AlterField(
            model_name='wareteams',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.manager'),
        ),
    ]
