# Generated by Django 4.0.1 on 2024-04-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_opteam_manager_alter_wareteams_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAddModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
